/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package currencyconverter;

import currencyconverter.Logic.Calculation;
import currencyconverter.Logic.Logic;
import currencyconverter.Model.ModelProgram;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Currency extends javax.swing.JFrame {
	
	/**
	 * Creates new form Login
	 */
	public Currency() {
		initComponents();
		Logic logic = new Logic();
		label_result.setText(logic.output);
		setLocationRelativeTo(this);
	}

	Currency(String name) {
		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_input = new javax.swing.JComboBox<>();
        tf_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_output = new javax.swing.JComboBox<>();
        btn_convert = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        label_result = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        label_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Century", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ü-Money");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Select your Input Currency :");

        cb_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rupiah", "Euro", "Dollar", "Yen" }));

        tf_input.setText("0");
        tf_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_inputKeyPressed(evt);
            }
        });

        jLabel3.setText("Select your Output Currency :");

        cb_output.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rupiah", "Euro", "Dollar", "Yen" }));

        btn_convert.setText("Convert");
        btn_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertActionPerformed(evt);
            }
        });

        jLabel4.setText("Converted Amount :");

        label_result.setText("-");

        btn_clear.setText("Clear");
        btn_clear.setMaximumSize(new java.awt.Dimension(74, 32));
        btn_clear.setMinimumSize(new java.awt.Dimension(74, 32));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        label_name.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_result))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cb_input, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tf_input, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cb_output, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(30, 30, 30))))))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_convert))
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_exit)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_name)
                        .addGap(225, 225, 225))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(label_name)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_convert)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(label_result))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btn_exit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertActionPerformed
		// TODO add your handling code here:
		String a = (String) cb_input.getSelectedItem();
		String b = (String) cb_output.getSelectedItem();
		String labelResult = label_result.getText();
		String enterInput = tf_input.getText();
		
		Logic logic = new Logic();
		ModelProgram modelProgram = new ModelProgram();
		
		clear();
		
//		double masukan = Double.parseDouble(enterInput);
//		tf_input.setText(Double.toString(masukan));
//		
//		DecimalFormat angka = new DecimalFormat("###,###");
//		
//		double keluar = Double.parseDouble(labelResult);
//		label_result.setText(Double.toString(keluar));
		int input = Integer.parseInt(enterInput);

		modelProgram.setInput(input);
		
		Calculation calculation = new Calculation();
//		calculation.calculate(masukan);
//		calculation.calculate(masukan, keluar);
		
	

		if (a.equals("Rupiah") && b.equals("Rupiah")) {
			String result = logic.idr_to_idr(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Rupiah") && b.equals("Euro")) {
			String result = logic.idr_to_eur(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Rupiah") && b.equals("Dollar")) {
			String result = logic.idr_to_usd(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Rupiah") && b.equals("Yen")) {
			String result = logic.idr_to_jpy(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Euro") && b.equals("Euro")) {
			String result = logic.eur_to_eur(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Euro") && b.equals("Rupiah")) {
			String result = logic.eur_to_idr(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Euro") && b.equals("Dollar")) {
			String result = logic.eur_to_usd(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Euro") && b.equals("Yen")) {
			String result = logic.eur_to_jpy(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Dollar") && b.equals("Dollar")) {
			String result = logic.usd_to_usd(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Dollar") && b.equals("Rupiah")) {
			String result = logic.usd_to_idr(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Dollar") && b.equals("Euro")) {
			String result = logic.usd_to_eur(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Dollar") && b.equals("Yen")) {
			String result = logic.usd_to_jpy(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Yen") && b.equals("Yen")) {
			String result = logic.jpy_to_jpy(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Yen") && b.equals("Rupiah")) {
			String result = logic.jpy_to_idr(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Yen") && b.equals("Euro")) {
			String result = logic.jpy_to_eur(modelProgram);
			label_result.setText(result);
		} else if (a.equals("Yen") && b.equals("Dollar")) {
			String result = logic.jpy_to_usd(modelProgram);
			label_result.setText(result);
		}
		
		tf_input.setText(enterInput);
    }//GEN-LAST:event_btn_convertActionPerformed

    private void tf_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_inputKeyPressed
		// TODO add your handling code here:
    }//GEN-LAST:event_tf_inputKeyPressed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
		// TODO add your handling code here:
		clear();
    }//GEN-LAST:event_btn_clearActionPerformed
	
	void clear(){
		ModelProgram modelProgram = new ModelProgram();

		modelProgram.setInput(0);

		tf_input.setText("0");
		label_result.setText("0");
		tf_input.requestFocus();
	}
	
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
		// TODO add your handling code here:
		int dialog = JOptionPane.showOptionDialog(this, "Are you sure?", "Exit",
				JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

		if (dialog == JOptionPane.YES_OPTION) {
			JOptionPane.showMessageDialog(this, "Thank you for using this program");
			System.exit(0);
		}
    }//GEN-LAST:event_btn_exitActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Currency().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_convert;
    private javax.swing.JButton btn_exit;
    private javax.swing.JComboBox<String> cb_input;
    private javax.swing.JComboBox<String> cb_output;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_result;
    private javax.swing.JTextField tf_input;
    // End of variables declaration//GEN-END:variables
}
